import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { polkadotHubTestnet } from "../hardhat.config";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

interface Deployments {
	evm: string | null;
	pvm: string | null;
	univerify: string | null;
	certificateNft: string | null;
}

function updateDeployments(key: string, address: string) {
	let data: Deployments = {
		evm: null,
		pvm: null,
		univerify: null,
		certificateNft: null,
	};
	try {
		data = { ...data, ...JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) };
	} catch {
		// File doesn't exist yet
	}
	(data as Record<string, string | null>)[key] = address;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
// Hosted builds may override any address through Vite env vars:
//   VITE_EVM_CONTRACT_ADDRESS
//   VITE_PVM_CONTRACT_ADDRESS
//   VITE_UNIVERIFY_CONTRACT_ADDRESS
//   VITE_CERTIFICATE_NFT_ADDRESS

function readOverride(value: string | undefined): string | null {
\tconst trimmed = value?.trim();
\treturn trimmed ? trimmed : null;
}

const generatedDeployments = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tuniverify: ${fmt(data.univerify)},
\tcertificateNft: ${fmt(data.certificateNft)},
} as const;

export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tuniverify: string | null;
\tcertificateNft: string | null;
} = {
\tevm: readOverride(import.meta.env.VITE_EVM_CONTRACT_ADDRESS) ?? generatedDeployments.evm,
\tpvm: readOverride(import.meta.env.VITE_PVM_CONTRACT_ADDRESS) ?? generatedDeployments.pvm,
\tuniverify:
\t\treadOverride(import.meta.env.VITE_UNIVERIFY_CONTRACT_ADDRESS) ??
\t\tgeneratedDeployments.univerify,
\tcertificateNft:
\t\treadOverride(import.meta.env.VITE_CERTIFICATE_NFT_ADDRESS) ??
\t\tgeneratedDeployments.certificateNft,
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying ProofOfExistence (EVM/solc)...");

	const isTestnet = hre.network.name === "polkadotTestnet";
	const chainOption = isTestnet ? { chain: polkadotHubTestnet } : {};

	const [walletClient] = await hre.viem.getWalletClients(chainOption);
	const publicClient = await hre.viem.getPublicClient(chainOption);
	const artifact = await hre.artifacts.readArtifact("ProofOfExistence");

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	console.log(`EVM ProofOfExistence deployed to: ${receipt.contractAddress}`);
	updateDeployments("evm", receipt.contractAddress);
	console.log("Updated deployments.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
