import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../web/src/config/deployments.ts");

interface Deployments {
	evm: string | null;
	pvm: string | null;
	univerify: string | null;
}

function updateDeployments(address: string) {
	let data: Deployments = { evm: null, pvm: null, univerify: null };
	try {
		data = { ...data, ...JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) };
	} catch {
		// File doesn't exist yet
	}
	data.univerify = address;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null; univerify: string | null } = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tuniverify: ${fmt(data.univerify)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Deploying Univerify...");

	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();
	const artifact = await hre.artifacts.readArtifact("Univerify");

	const hash = await walletClient.deployContract({
		abi: artifact.abi,
		bytecode: artifact.bytecode as `0x${string}`,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	const contractAddress = receipt.contractAddress;
	console.log(`Univerify deployed to: ${contractAddress}`);

	// Register the deployer (Alice) as an authorized issuer for dev convenience
	const deployer = walletClient.account.address;
	console.log(`Registering deployer ${deployer} as authorized issuer...`);

	const issuerMetadataHash =
		"0x0000000000000000000000000000000000000000000000000000000000000001" as `0x${string}`;

	const regHash = await walletClient.writeContract({
		address: contractAddress,
		abi: artifact.abi,
		functionName: "registerIssuer",
		args: [deployer, issuerMetadataHash],
	});
	await publicClient.waitForTransactionReceipt({ hash: regHash, timeout: 120_000 });
	console.log("Deployer registered as issuer.");

	updateDeployments(contractAddress);
	console.log("Updated deployments.json and deployments.ts");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
