import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { isAddress, isHex, size, type Address, type Hex } from "viem";

const REPO_ROOT = path.resolve(__dirname, "../../..");
const DEPLOYMENTS_JSON = path.join(REPO_ROOT, "deployments.json");
const DEPLOYMENTS_TS = path.join(REPO_ROOT, "web/src/config/deployments.ts");
const CONFIG_DIR = path.resolve(__dirname, "../config");

// Must match Univerify.sol `MAX_NAME_LENGTH` exactly.
const MAX_NAME_LENGTH = 64;

interface GenesisIssuerConfig {
	account: string;
	name: string;
	metadataHash: string;
}

interface GenesisConfig {
	approvalThreshold: number;
	issuers: GenesisIssuerConfig[];
}

interface Deployments {
	evm: string | null;
	pvm: string | null;
	univerify: string | null;
	certificateNft: string | null;
}

function loadGenesisConfig(networkName: string): GenesisConfig {
	const file = path.join(CONFIG_DIR, `genesis-${networkName}.json`);
	if (!fs.existsSync(file)) {
		throw new Error(
			`Genesis config not found at ${file}.\n` +
				`Copy contracts/evm/config/genesis-${networkName}.example.json to ` +
				`genesis-${networkName}.json and fill in the real issuer set.`,
		);
	}

	let raw: unknown;
	try {
		raw = JSON.parse(fs.readFileSync(file, "utf-8"));
	} catch (e) {
		throw new Error(`${file}: invalid JSON — ${(e as Error).message}`);
	}
	if (!raw || typeof raw !== "object") {
		throw new Error(`${file}: expected a JSON object at the top level.`);
	}

	const cfg = raw as GenesisConfig;

	if (!Number.isInteger(cfg.approvalThreshold) || cfg.approvalThreshold < 1) {
		throw new Error(
			`${file}: "approvalThreshold" must be a positive integer (got ${JSON.stringify(
				cfg.approvalThreshold,
			)}).`,
		);
	}
	if (!Array.isArray(cfg.issuers) || cfg.issuers.length === 0) {
		throw new Error(`${file}: "issuers" must be a non-empty array.`);
	}
	if (cfg.approvalThreshold > cfg.issuers.length) {
		throw new Error(
			`${file}: approvalThreshold (${cfg.approvalThreshold}) must not exceed issuers.length (${cfg.issuers.length}).`,
		);
	}

	const seen = new Set<string>();
	cfg.issuers.forEach((issuer, i) => {
		if (!issuer || typeof issuer !== "object") {
			throw new Error(`${file}: issuers[${i}] must be an object.`);
		}
		if (!isAddress(issuer.account)) {
			throw new Error(
				`${file}: issuers[${i}].account is not a valid Ethereum address (got ${JSON.stringify(
					issuer.account,
				)}).`,
			);
		}
		const lower = issuer.account.toLowerCase();
		if (seen.has(lower)) {
			throw new Error(
				`${file}: issuers[${i}].account (${issuer.account}) duplicates an earlier entry.`,
			);
		}
		seen.add(lower);

		if (typeof issuer.name !== "string" || issuer.name.length === 0) {
			throw new Error(`${file}: issuers[${i}].name must be a non-empty string.`);
		}
		const nameBytes = Buffer.byteLength(issuer.name, "utf8");
		if (nameBytes > MAX_NAME_LENGTH) {
			throw new Error(
				`${file}: issuers[${i}].name is ${nameBytes} bytes; the contract caps it at ${MAX_NAME_LENGTH}.`,
			);
		}

		if (!isHex(issuer.metadataHash) || size(issuer.metadataHash as Hex) !== 32) {
			throw new Error(
				`${file}: issuers[${i}].metadataHash must be a 0x-prefixed 32-byte value (got ${JSON.stringify(
					issuer.metadataHash,
				)}).`,
			);
		}
	});

	return cfg;
}

function updateDeployments(univerify: string, certificateNft: string) {
	let data: Deployments = {
		evm: null,
		pvm: null,
		univerify: null,
		certificateNft: null,
	};
	try {
		data = { ...data, ...JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8")) };
	} catch {
		// File doesn't exist yet — the default above is the seed.
	}
	data.univerify = univerify;
	data.certificateNft = certificateNft;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: {
\tevm: string | null;
\tpvm: string | null;
\tuniverify: string | null;
\tcertificateNft: string | null;
} = {
\tevm: ${fmt(data.evm)},
\tpvm: ${fmt(data.pvm)},
\tuniverify: ${fmt(data.univerify)},
\tcertificateNft: ${fmt(data.certificateNft)},
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	const networkName = hre.network.name;
	console.log(`Deploying Univerify to network: ${networkName}`);

	const config = loadGenesisConfig(networkName);
	console.log(
		`Loaded genesis: ${config.issuers.length} issuer(s), approvalThreshold=${config.approvalThreshold}`,
	);
	for (const issuer of config.issuers) {
		console.log(`  - ${issuer.name} (${issuer.account})`);
	}

	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();
	const univerifyArtifact = await hre.artifacts.readArtifact("Univerify");
	const nftArtifact = await hre.artifacts.readArtifact("CertificateNft");

	const genesisArg = config.issuers.map((i) => ({
		account: i.account as Address,
		name: i.name,
		metadataHash: i.metadataHash as Hex,
	}));

	// 1) Deploy Univerify (no NFT wired yet — `certificateNft` defaults to 0).
	const univerifyHash = await walletClient.deployContract({
		abi: univerifyArtifact.abi,
		bytecode: univerifyArtifact.bytecode as Hex,
		args: [genesisArg, config.approvalThreshold],
	});
	const univerifyReceipt = await publicClient.waitForTransactionReceipt({
		hash: univerifyHash,
		timeout: 120_000,
	});
	if (!univerifyReceipt.contractAddress) {
		throw new Error(`Deploy tx ${univerifyHash} did not create a contract`);
	}
	const univerifyAddress = univerifyReceipt.contractAddress;
	console.log(`Univerify        deployed to: ${univerifyAddress}`);

	// 2) Deploy the soulbound NFT contract pointing back at Univerify.
	const nftHash = await walletClient.deployContract({
		abi: nftArtifact.abi,
		bytecode: nftArtifact.bytecode as Hex,
		args: [univerifyAddress, univerifyAddress],
	});
	const nftReceipt = await publicClient.waitForTransactionReceipt({
		hash: nftHash,
		timeout: 120_000,
	});
	if (!nftReceipt.contractAddress) {
		throw new Error(`Deploy tx ${nftHash} did not create a contract`);
	}
	const nftAddress = nftReceipt.contractAddress;
	console.log(`CertificateNft   deployed to: ${nftAddress}`);

	// 3) Wire the NFT into Univerify (one-shot setter, owner-only).
	const wireHash = await walletClient.writeContract({
		address: univerifyAddress,
		abi: univerifyArtifact.abi,
		functionName: "setCertificateNft",
		args: [nftAddress],
	});
	await publicClient.waitForTransactionReceipt({ hash: wireHash, timeout: 120_000 });
	console.log(`setCertificateNft tx:        ${wireHash}`);
	console.log(`Owner (deployer):             ${walletClient.account.address}`);

	updateDeployments(univerifyAddress, nftAddress);
	console.log("Updated deployments.json and web/src/config/deployments.ts");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
