// Auto-generated by contract deploy scripts — do not edit manually
// Hosted builds may override any address through Vite env vars:
//   VITE_EVM_CONTRACT_ADDRESS
//   VITE_PVM_CONTRACT_ADDRESS
//   VITE_UNIVERIFY_CONTRACT_ADDRESS
//   VITE_CERTIFICATE_NFT_ADDRESS

function readOverride(value: string | undefined): string | null {
	const trimmed = value?.trim();
	return trimmed ? trimmed : null;
}

const generatedDeployments = {
	evm: "0x6f364ba017935cc6207b07738cb0fb512dc7751c",
	pvm: "0x2a1454b3ba3290c3f9502313189a1f2d970ec31e",
	univerify: "0xfbd19395bf0bdb0298ecce6148cb38ff1c52cf6e",
	certificateNft: "0x17e154577547441b420134659ebe6b3e57ee1823",
} as const;

export const deployments: {
	evm: string | null;
	pvm: string | null;
	univerify: string | null;
	certificateNft: string | null;
} = {
	evm: readOverride(import.meta.env.VITE_EVM_CONTRACT_ADDRESS) ?? generatedDeployments.evm,
	pvm: readOverride(import.meta.env.VITE_PVM_CONTRACT_ADDRESS) ?? generatedDeployments.pvm,
	univerify:
		readOverride(import.meta.env.VITE_UNIVERIFY_CONTRACT_ADDRESS) ??
		generatedDeployments.univerify,
	certificateNft:
		readOverride(import.meta.env.VITE_CERTIFICATE_NFT_ADDRESS) ??
		generatedDeployments.certificateNft,
};
