// Auto-generated by contract deploy scripts — do not edit manually
// Hosted builds may override any address through Vite env vars:
//   VITE_EVM_CONTRACT_ADDRESS
//   VITE_PVM_CONTRACT_ADDRESS
//   VITE_UNIVERIFY_CONTRACT_ADDRESS
//   VITE_CERTIFICATE_NFT_ADDRESS

function readOverride(value: string | undefined): string | null {
	const trimmed = value?.trim();
	return trimmed ? trimmed : null;
}

const generatedDeployments = {
	evm: "0x6f364ba017935cc6207b07738cb0fb512dc7751c",
	pvm: "0xf92b1c1001df3b23a7acc85d1267024322d12ad3",
	univerify: "0x6d31f4753116d9b90a38c2df32d9e452dd57dd46",
	certificateNft: "0x89c723f86870631b642b36959fe02e982d8db125",
} as const;

export const deployments: {
	evm: string | null;
	pvm: string | null;
	univerify: string | null;
	certificateNft: string | null;
} = {
	evm: readOverride(import.meta.env.VITE_EVM_CONTRACT_ADDRESS) ?? generatedDeployments.evm,
	pvm: readOverride(import.meta.env.VITE_PVM_CONTRACT_ADDRESS) ?? generatedDeployments.pvm,
	univerify:
		readOverride(import.meta.env.VITE_UNIVERIFY_CONTRACT_ADDRESS) ??
		generatedDeployments.univerify,
	certificateNft:
		readOverride(import.meta.env.VITE_CERTIFICATE_NFT_ADDRESS) ??
		generatedDeployments.certificateNft,
};
