// Auto-generated by contract deploy scripts — do not edit manually
// Hosted builds may override any address through Vite env vars:
//   VITE_EVM_CONTRACT_ADDRESS
//   VITE_PVM_CONTRACT_ADDRESS
//   VITE_UNIVERIFY_CONTRACT_ADDRESS
//   VITE_CERTIFICATE_NFT_ADDRESS

function readOverride(value: string | undefined): string | null {
	const trimmed = value?.trim();
	return trimmed ? trimmed : null;
}

const generatedDeployments = {
	evm: "0x6f364ba017935cc6207b07738cb0fb512dc7751c",
	pvm: "0xf92b1c1001df3b23a7acc85d1267024322d12ad3",
	univerify: "0x16b745af41b9c2da7867c6b979ccb0ab35bda135",
	certificateNft: "0x534a5c1d3763ad666d83a14894deb1a6da4896f9",
} as const;

export const deployments: {
	evm: string | null;
	pvm: string | null;
	univerify: string | null;
	certificateNft: string | null;
} = {
	evm: readOverride(import.meta.env.VITE_EVM_CONTRACT_ADDRESS) ?? generatedDeployments.evm,
	pvm: readOverride(import.meta.env.VITE_PVM_CONTRACT_ADDRESS) ?? generatedDeployments.pvm,
	univerify:
		readOverride(import.meta.env.VITE_UNIVERIFY_CONTRACT_ADDRESS) ??
		generatedDeployments.univerify,
	certificateNft:
		readOverride(import.meta.env.VITE_CERTIFICATE_NFT_ADDRESS) ??
		generatedDeployments.certificateNft,
};
